name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash



    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install
      run:
        npm ci

    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master
      with:
        path: .

    - name: Load API Config
      run: |
          echo 'REACT_APP_API_KEY=${{ secrets.FIREBASE_API_KEY_DEV }}' >> .env.production
          echo 'REACT_APP_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN_DEV }}' >> .env.production
          echo 'REACT_APP_DATABASE_URL=${{ secrets.FIREBASE_DATABASE_URL_DEV }}' >> .env.production
          echo 'REACT_APP_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID_DEV }}' >> .env.production
          echo 'REACT_APP_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET_DEV }}' >> .env.production
          echo 'REACT_APP_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID_DEV }}' >> .env.production
          echo 'REACT_APP_APP_ID=${{ secrets.FIREBASE_APP_ID_DEV }}' >> .env.production
          echo 'REACT_APP_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID_DEV }}' >> .env.production
          echo 'REACT_APP_CONFIRMATION_EMAIL_REDIRECT=${{ secrets.EMAIL_REDIRECT_DEV }}' >> .env.production
          echo 'REACT_APP_SENTRY_DSN=${{ secrets.SENTRY_DSN }}' >> .env.production
          echo 'REACT_APP_VERSION=${{ steps.package-version.outputs.current-version}}' >> .env.production
          echo 'REACT_APP_COLLEGE_ACRONYM=CCAFC' >> .env.production
          echo 'REACT_APP_COLLEGE_NAME=Collingwood' >> .env.production

    - name: Build
      run: 
        npm run build
      env:
        CI: true

