version: 2
workflows:
  version: 2
  build:
    jobs:
      - test_client
      - deploy_firebase_functions_production

jobs:
  test_client:
    working_directory: ~/fantasy/src
    docker:
      - image: circleci/node:10.15.1
        environment:
          TZ: Europe/London
    steps:
      - checkout:
          path: ~/fantasy
      - run:
          name: Installations 
          command: npm ci
      - run:
          name: Lint
          command: |
            ls
            npm run lint
      - run:
          name: Run Tests
          command: npm test

  deploy_firebase_functions_production:
    working_directory: ~/fantasy/functions
    docker:
      - image: circleci/node:10.15.1
    steps:
      - checkout:
          path: ~/fantasy
      - run:
          name: Installations 
          command: npm ci
      - run:
          name: Deploy to firebase functions
          command: |
              npm install -g firebase-tools
              npx firebase deploy --only functions --token "$FIREBASE_TOKEN"