name: Build and Test
on: 
  push:
    branches-ignore:
      - master
      - develop

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - id: foo 
      uses: MatthewFennell/ccafc-fantasy-football@v1
      with:
        who-to-greet: 'Mona the Octocat'
    - run: echo random-number ${{ steps.foo.outputs.random-number }}
      shell: bash

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install
      run:
        npm ci
    - name: Build
      run: 
        npm run build
      env:
        CI: true

    - name: Lint
      run:
        npm run lint
      env:
        CI: true   

    - name: Testing
      run:
        npm test
      env:
        CI: true