name: Build and Test
on: 
  push:
    branches-ignore:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install
      run:
        npm ci
    - name: Build
      run: 
        npm run build
      env:
        CI: true

    - name: list
      run:
        ls

    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master
      with:
        path: ./

    - name: Lint
      run:
        npm run lint
      env:
        CI: true   

    - name: Testing
      run:
        npm test:coverage
      env:
        CI: true